site_name: mlsauce
theme:
  name: darkly # sandstone # slate # lux # darkly
  nav_style: dark
  #name: null
  #custom_dir: 'custom_theme/'


docs_dir: sources
repo_url: https://github.com/Techtonique/mlsauce
edit_uri: ""
site_description: 'Documentation for the mlsauce.'

nav:
    - Quickstart examples:
      - Classification: examples/classification.md
      - Regression: examples/regression.md
    - Documentation:
      - Classifiers: documentation/classifiers.md
      - Regressors: documentation/regressors.md
      - Scoring metrics: documentation/scoring_metrics.md
    - Contributing: CONTRIBUTING.md  
    - License: LICENSE.md  
    - References: REFERENCES.md
    - Techtonique: ../../
    