name: Publish Python 🐍 distribution 📦 to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install wheel setuptools twine Cython

      - name: Build distribution
        run: python3 setup.py sdist

      #- name: Run examples 
      #  run: pip install .&&find examples -maxdepth 2 -name "*boost_*.py" -exec  python3 {} \;

      - name: Publish to PyPI                
        uses: pypa/gh-action-pypi-publish@release/v2
        with:
           password: ${{ secrets.PYPI_GLOBAL_MLSAUCE2 }}
           repository-url: https://upload.pypi.org/legacy/          
